var GAME_LEVELS = [
  ["                                                                                ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvxxxxxxxxxxxxxxxxxxxxxxxxvxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                ",
   "                                                                                ",
   "          yy                                                       o            ",
   "            y                                       o       o     xxx           ",
   "             y                 y             o     xx      xx    xx!xx          ",
   "                              yyy            xx                  x!!!x          ",
   "                             y                        yy         xx!xx          ",
   "      y        yy                  xxxxxyy              yy        xvx           ",
   "              y               h       y                   yy  xx            xx  ",
   "  xx         y                            o o                          o     x  ",
   "  x                     o                                                o   x  ",
   "  x                                        xxxxx                           o x  ",
   "  x          xxxxx       o                                                   x  ",
   "  x  @       x!!!x   z                                            xxxxx      x  ",
   "  xxxxxxxxxxxx!!!xxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "               v              x   x                  x     x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                        !!!!!!!                                               ",
   "              yyy                                      x!!!!!!!!x                                             ",
   "xxxxxxxxyyyyyyyy     h    o                             x!!!!!!x                                              ",
   "      xxx!!!!!!!!!!yyxxxxxxx              yy             x!!!!x                        yyyy                   ",
   "        xxx!!!!!!!!!!!xxx   xxxx o o            y          v                        yyyy                      ",
   "          xxxxxx!!!!xxx         xxxx            yy                                                    o o o   ",
   "                   v                                                                                 xxxxxxx  ",
   " z                                        o o                                oyyy                             ",
   "  yy                                     xxxxxx                             xxx                               ",
   " y                                                yy                                 xxxxxxxxyy               ",
   "y            o                 yy               y                                         x!!!!y              ",
   "            o               yy                    o o                                        v                ",
   "                                                  xxxx                         o  o                           ",
   "                               x                                            xxxxxxxx                          ",
   "                                                                         o                                    ",
   " @                                                                     o                                      ",
   "xxxx                                               xxxxxxx       xxxxxxxxxxx                     xxxxxx       ",
   "   xxxxx                xxxx        xxxxxx                               yyyy                                 ",
   "       xxxxx            xxxx!!!!!!!!!!!!!y                                     y                              ",
   "           xxxx       xxxxxx!!!xxxxxxxxxyy                                         y                          ",
   "    y         xxx       xxxx!!x  o   hy      xxxxxx                                                           ",
   "      yyy       x!!!!!!!xxxx!    o  yy                                                                        ",
   "                x!!!!!!!xxxx!z   o                                                                            ",
   "                x!!!!!!!xxxx!xxxxxxxxxxxxxxx                                                                  ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                   v                                   !!!!!!!!!                  !!!!!!!                     ",
   "                                                         !!!!!!                     !!!                       ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                             "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "              !!!!!!!!!!                o                                              !!!!!!!!!!!!!          ",
   "                  yy!!!!!!!                                                                !!!!!!             ",
   "                          v                                                                  !!!!             ",
   "                                        o                            y yy y                    v              ",
   "                          v                                        y        y                                 ",
   "                                        o                         y     o     y                v              ",
   "                         y                                                                                    ",
   "                                                x x                !!!         !!!                            ",
   "                                                 x x              xxxxy        !y! yyyyy                      ",
   "                           o o        xxx   xx                                        xx                      ",
   "                          x   x       o         x   oooo                              xxxxx  yyyyyy           ",
   "                    z                  o                                                 xxxxx                ",
   "      yyyy                        y    o          x                     xxxxxxxxxxxx!!!!!!!!xxxxx             ",
   "                  y  y                        xx   xx      x   x      x           xx          xxxxx yyyyy h   ",
   "                   y             y          x   xxxxxxxxx   xxxxxxxx                xx!!!!!!!!!!!!xxxx   xxx  ",
   "                 y                  xxx    x         y x     yy             x!!!x     xxx   yyyyyyyyyyyy      ",
   "                                  y  x    x           x                     xxx          xxxx!!!!!!!!!!!!!!   ",
   "                                    x                                                    yyxxxx               ",
   "                                     y           y           xxx                             xxxxxx           ",
   "                                                x           x!!!x                                xxxx         ",
   "                                            o      xxx      hxxx                                    o         ",
   "                 yyyy                    x   xx                            x!!!x                              ",
   "                              o   o   x   x yy          x   xxx y          xxv        xxx             o       ",
   "                                      x y  x           x     yy        x                                      ",
   "       yyyy                      xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x                   x         o      ",
   "  yyy                             xxx xxx xxx x          x!!!!!!!!!!!!!!x                                     ",
   "                                          x   xxxxxxxxxxxxxxxxxxxxxxx v z                               o     ",
   "                             xx     h     xx                                         xxx                      ",
   "  xxx          y              x          x                                                       y o    xxxxxx",
   "  x x          y              x    x  x    x                              yy  x      xxx         y o     x    ",
   "  x             y        xxx  x    xxx    xxxxxxx         o                xx!!x                     y y      ",
   "  x    y   o        o         x           x               o                x!!!x                           x  ",
   "  x  y     o  y     o         xxx          x              o                x x x                           x  ",
   "  xz       o   y    o                     x      xxxx   o   o    xxx                                 x        ",
   "  x        o       xxx             o o    x z          o     o                      xxx                    x  ",
   "  x        o      xxxxx       xx          x          o         o        xxx        x!!!x                   x  ",
   "  x                      x    xxx    x    !                        x x        xxx          xxx                ",
   "  x                        xxxxxxxxxxxxx!!!x o o     o o o o  o o x       xx xx                    xxx       x",
   "  x      @                  x           x!!x        xyyyyx    xx   xx                    y         y          ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                              ",
   "                                                                                                  xxxxx       ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "            @       y       y      yyy      y      y                                                          ",
   "                     y     y      y   y     y      y                                                          ",
   "                      y   y      y     y    y      y                                                          ",
   "                       y y      y       y   y      y                                                          ",
   "                        y       y       y   y      y                                                          ",
   "                        y        y     y    y      y                                                          ",
   "                        y         y   y      y    y                                       y                   ",
   "                        y          yyy        yyyy        y      y  yyyyy   yy      y     y                   ",
   "                                                          y      y    y     y y     y     y                   ",
   "                                                          y      y    y     y  y    y     y                   ",
   "                                                          y      y    y     y   y   y     y                   ",
   "                                                          y  yy  y    y     y    y  y                         ",
   "                                                          y y  y y    y     y     y y     y                   ",
   "                                                          yy    yy  yyyyy   y      y                          ",
   "  xxxxxxxxxxx   o o o o o o o o o o o o o o o o o                                                             ",
   "        x                                              o                                                      ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     o o o o o o o o o o o o o o o o o o o o               ",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
